apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - disallow-privileged.yaml
  - require-non-root.yaml
  - require-ro-rootfs.yaml
  - require-drop-capabilities.yaml
  - disallow-privilege-escalation.yaml
  - disallow-host-namespaces.yaml
