apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/kyverno
  - ../base/network-policies
  - ../base/monitoring
  # - ../base/cert-manager
patches:
  # Production-specific patches - larger retention and resources
  - target:
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
    patch: |-
      - op: replace
        path: /spec/values/prometheus/prometheusSpec/retention
        value: 30d
      - op: replace
        path: /spec/values/prometheus/prometheusSpec/retentionSize
        value: 50GB
  - target:
      kind: HelmRelease
      name: loki
      namespace: monitoring
    patch: |-
      - op: replace
        path: /spec/values/loki/limits_config/retention_period
        value: 720h
      - op: replace
        path: /spec/values/singleBinary/persistence/size
        value: 50Gi
