apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base/secure-demo-app
patches:
  - target:
      kind: Deployment
      name: secure-demo-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
