apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/kyverno
  - ../base/network-policies
  - ../base/monitoring
  # - ../base/cert-manager
patches:
  # Staging-specific patches
  - target:
      kind: HelmRelease
      name: loki
      namespace: monitoring
    patch: |-
      - op: replace
        path: /spec/values/singleBinary/persistence/size
        value: 5Gi
